var SV=window.SV||{};SV.LiveContent=SV.LiveContent||{};
(function(k,q,r,u){SV.LiveContent=k.extend({debug:!0,stopped:!1,pollingMethod:"GET",fastPolling:0,slowPolling:0,url:"",initialDate:0},SV.LiveContent);k(r).on("xf:page-load-complete",function(){if("localStorage"in q&&q.localStorage.length){Date.now||(Date.now=function(){return(new Date).getTime()});var a=Date.now()/1E3|0,d=q.localStorage,e=d.getItem("liveContent:gc");if(!e||e<a-86400){d.setItem("liveContent:gc",a);a-=172800;e=[];for(var g=0;g<d.length;g++){var h=d.key(g),f=h.match(/^(NchanSubscriber:\/.*?\/live:shared:)msg:id$/);
if(f){var l=d.getItem(h).split(":");if(!l||l[0]<a)f=f[1],e.push(h),e.push(f+"status"),e.push(f+"lottery"),e.push(f+"lotteryTime"),e.push(f+"master:created"),e.push(f+"master:lastSeen"),e.push(f+"msg:content-type"),e.push(f+"msg")}}for(g=0;g<e.length;g++)d.removeItem(e[g])}}if(SV.LiveContent.url){var b=new NchanSubscriber(SV.LiveContent.url,{subscriber:"longpoll",reconnect:!1,shared:!0}),m=!1,n=null;b.on("transportSetup",function(a,d){"longpoll"===d?(a.headers.xfToken=XF.config.csrf,a.headers.Etag=
SV.LiveContent.initialDate,a.longpoll.pollDelay=SV.LiveContent.slowPolling,a.longpoll.method=SV.LiveContent.pollingMethod,k('[data-xf-init~="quick-reply"]').on("ajax-submit:before",function(){m=!0;n||(n=setTimeout(function(){m=!1},2*SV.LiveContent.slowPolling),"longpoll"===b.transport.name&&b.transport.reschedulePendingPollRequest(SV.LiveContent.fastPolling))})):console.log("Live Content - waiting for other-tab to send events")});b.on("message",function(a,d){if(a){try{var c=k.parseJSON(a)}catch(t){console.log(t,
a);SV.LiveContent.stopped=!0;b.stop();return}"status"in c?("visitor"in c&&XF.updateVisitorCounts(c.visitor,!b.shared||"master"===b.shared.role),"empty"===c.status?"date"in c&&c.date&&(b.transport.opt.headers.Etag=c.date):"error"===c.status?(console.log("Live Content error:",c),SV.LiveContent.stopped=!0,b.stop()):"ok"===c.status?"t"in c&&c.t?(b.transport.opt.longpoll.pollDelay=m||"more"in c&&c.more?SV.LiveContent.fastPolling:SV.LiveContent.slowPolling,SV.LiveContent.debug&&console.log("New "+c.t,", UserId:",
c.usr,", Id:",c.id,", Date:",c.date),b.transport.opt.headers.Etag=c.date,k(r).trigger("live-update."+c.t,c)):(console.log("Live Content malformed response:",c),SV.LiveContent.stopped=!0,b.stop()):(console.log("Live Content malformed response:",c),SV.LiveContent.stopped=!0,b.stop())):(console.log("Live Content malformed response:",c),SV.LiveContent.stopped=!0,b.stop())}else console.log("Live Content - Empty body, aborting"),SV.LiveContent.stopped=!0,b.stop()});b.on("connect",function(){console.log("Live Content - connecting");
delete b.transport.opt.headers.Etag});b.on("disconnect",function(a){console.log("Live Content - stopping");SV.LiveContent.stopped=!0});b.on("error",function(a,d){304===a?setTimeout(function(){SV.LiveContent.stopped=!0;"longpoll"===b.transport.name&&(SV.LiveContent.stopped=!1,b.transport.reschedulePendingPollRequest(SV.LiveContent.slowPolling))},0):(404===a?console.log("Live Content - stopping"):console.log("Live Content - stopping, http error:",a,d),b.running&&b.stop(),SV.LiveContent.stopped=!0)});
d="keepAlive"+XF.stringHashCode(XF.config.url.keepAlive);XF.CrossTab.on(d,function(a){a.csrf&&b.transport&&(b.transport.opt.headers.xfToken=a.csrf)});b.start();SV.LiveContent.stopped=!1}else console.log("No liver content url")});SV.LiveContent.OldNewMessageIndicator=XF.Element.newHandler({options:{messageSelector:null,svLiveContentTimeElementSelector:null,svLiveContentUnreadClassName:"is-unread"},messagesObserver:null,init:function(){if(this.options.messageSelector)if(this.options.svLiveContentTimeElementSelector){this.messagesObserver||
(this.messagesObserver=new IntersectionObserver(XF.proxy(this,"interactionObserverCallback")));var a=this;this.$target.find(this.options.messageSelector).each(function(){a.messagesObserver.observe(this)})}else console.error("No time selector provided.");else console.error("No message selector provided.")},interactionObserverCallback:function(a){var d=this.options.svLiveContentUnreadClassName,e=null,g=null,h=null,f=null,l=null,b=null,m=null,n=0,p=0;k.each(a,function(){var a=k(this.target),c=a.hasClass(d);
c&&(null===e&&(e=a),n++);this.isIntersecting?(null===g&&(g=a),h=a,c&&null===b&&(b=a)):(null===f&&(f=a),l=a,c&&(null===m&&(m=a),p++))});n?p&&p?this.showUnreadMessagesBar(p,g):this.hideUnreadMessagesBar():this.hideUnreadMessagesBar();h&&l&&this.isOlderMessage(h)?this.showViewingOldMessagesBar(h,l):this.hideViewingOldMessagesBar()},isOlderMessage:function(a,d){d=(d=parseInt(d))||86400;var e=Math.round(+new Date/1E3);a=a.find(this.options.svLiveContentTimeElementSelector);if(a.length)return parseInt(a.data("time"))<=
e-d;console.error("No date element available for provided message.")},getUnreadMessagesBarType:function(){return"unread-messages"},showUnreadMessagesBar:function(a,d){var e=this,g=String(a),h=this.getUnreadMessagesBarType();a=k('.message[data-sv-live-content-bar-type="'+h+'"]');var f=function(){e.hideUnreadMessagesBar();k('<div class="message" data-sv-live-content-bar-type="'+h+'" data-unread-count="'+g+' ">   <div class="message-inner">      <div class="message-cell message-cell--alert">'+XF.phrase("svLiveContent_x_new_messages",
{"{unreadCount}":g})+"      </div>   </div></div>").insertBefore(d)};0===a.length?f():1===a.length?d.prev().data("sv-live-content-bar-type")===h?(a.data("unread-count",g),a.find("message-cell--alert").text(XF.phrase("svLiveContent_x_new_messages",{"{unreadCount}":g}))):f():f()},hideUnreadMessagesBar:function(){this.removeBar(this.getUnreadMessagesBarType())},getViewingOldMessagesBarType:function(){return"old-messages"},showViewingOldMessagesBar:function(a,d){var e=this,g=this.getViewingOldMessagesBarType(),
h=k('.message[data-sv-live-content-bar-type="'+g+'"]'),f=function(){e.hideViewingOldMessagesBar();k('<div class="message" data-sv-live-content-bar-type="'+g+'">   <div class="message-inner">      <div class="message-cell message-cell--alert">'+XF.phrase("svLiveContent_viewing_old_messages",{"{id}":d.attr("id")})+"      </div>   </div></div>").insertAfter(a)};0===h.length?f():1===h.length?a.next().data("sv-live-content-bar-type")===g?h.find("message-cell--alert").text(XF.phrase("svLiveContent_viewing_old_messages",
{"{id}":d.attr("id")})):f():f()},hideViewingOldMessagesBar:function(){this.removeBar(this.getViewingOldMessagesBarType())},removeBar:function(a){this.$target.find('[data-sv-live-content-bar-type="'+XF.htmlspecialchars(a)+'"]').each(function(){var a=k(this);a.xfFadeUp(XF.config.speed.xxfast,function(){a.remove()})})}})})(jQuery,window,document);
