(function(e,q,g){var m=g(e);"object"===typeof module&&null!=module&&module.exports?module.exports=m:"function"===typeof define&&define.amd?define(function(){return m}):e[q]=m})("undefined"!==typeof window?window:this,"NchanSubscriber",function(e,q){function g(b){if(b)for(var a in g.prototype)b[a]=g.prototype[a];else b=void 0;return b}function m(b,a){if("undefined"!==typeof window&&this===window)throw"use 'new NchanSubscriber(...)' to initialize";this.url=b;a=a||{};"string"===typeof a&&(a={subscriber:a});
a.transport&&!a.subscriber&&(a.subscriber=a.transport);"string"===typeof a.subscriber&&(a.subscriber=[a.subscriber]);this.desiredTransport=a.subscriber;if(a.shared){if(!("localStorage"in e))throw"localStorage unavailable for use in shared NchanSubscriber";var c="NchanSubscriber:"+this.url+":shared:",f=e.localStorage;this.shared={id:""+Math.random()+Math.random(),key:function(a){return c+a},get:function(a){return f.getItem(c+a)},set:function(a,b){return f.setItem(c+a,b)},setWithId:d(function(a,b){return this.shared.set(a,
"##"+this.shared.id+":"+b)},this),getWithId:d(function(a){return this.shared.stripIdFromVal(this.shared.get(a))},this),stripIdFromVal:function(a){if(!a)return a;var b=a.indexOf(":");return a[0]==a[1]&&"#"==a[0]&&b?a.substring(b+1,a.length):a},remove:function(a){return f.removeItem(c+a)},matchEventKey:d(function(a,b){return a.storageArea&&a.storageArea!=f?!1:a.key==c+b},this),matchEventKeyWithId:d(function(a,b){return this.shared.matchEventKey(a,b)?(a=a.newValue,b=a.indexOf(":"),a[0]==a[1]&&"#"==a[0]&&
b?a.substring(2,b)!=this.shared.id:!0):!1},this),setRole:d(function(a){if("master"==a&&"master"!=this.shared.role){var b=(new Date).getTime()/1E3;this.shared.setWithId("master:created",b);this.shared.setWithId("master:lastSeen",b)}"slave"!=a||this.lastMessageId||(this.lastMessageId=this.shared.get("msg:id"));this.shared.role=a;return this},this),demoteToSlave:d(function(){if("master"!=this.shared.role)throw"can't demote non-master to slave";this.running?(this.stop(),this.shared.setRole("slave"),this.initializeTransport(),
this.start()):this.initializeTransport()},this),maybePromoteToMaster:d(function(){if(!this.running&&!this.starting)return this;if(!this.shared.maybePromotingToMaster){this.shared.maybePromotingToMaster=!0;var a=0,b=Math.random(),c=b,f=d(function(a){var b=parseFloat(this.shared.getWithId("lotteryTime")),f=parseFloat(this.shared.getWithId("lottery"));(!b||b>(new Date).getTime()-4E3)&&f&&(!c||f>c)&&(c=f);a||t()},this);f(!0);this.shared.setWithId("lottery",b);this.shared.setWithId("lotteryTime",(new Date).getTime()/
1E3);var k=d(function(b){if(this.shared.matchEventKeyWithId(b,"lottery")&&b.newValue){a+=1;var f=parseFloat(this.shared.stripIdFromVal(b.newValue));b=parseFloat(this.shared.stripIdFromVal(b.oldValue));b>f&&this.shared.setWithId("lottery",b);if(!c||f>=c)c=f}},this);e.addEventListener("storage",k);var h=d(function(){this.shared.maybePromotingToMaster=!1;e.removeEventListener("storage",k);n&&clearInterval(n);this.shared&&"master"==this.shared.role&&(this.shared.remove("lottery"),this.shared.remove("lotteryTime"));
this.running?(this.stop(),this.initializeTransport(),this.start()):(this.initializeTransport(),this.starting&&this.start())},this);var t=d(function(){b<c?(this.shared.setRole("slave"),h()):b>=c&&(0==a?(this.shared.setRole("master"),h()):a=0)},this);var n=e.setInterval(f,2E3)}},this),masterCheckInterval:1E4}}this.lastMessageId=a.id||a.msgId;this.reconnect="undefined"==typeof a.reconnect?!0:a.reconnect;this.reconnectTimeout=a.reconnectTimeout||1E3;if(a.reconnect){var h="NchanSubscriber:"+b+":lastMessageId";
if("persist"==a.reconnect){var k="localStorage"in e&&e.localStorage;if(!k)throw"can't use reconnect: 'persist' option: localStorage not available";}else if("session"==a.reconnect){if(k="sessionStorage"in e&&e.sessionStorage,!k)throw"can't use reconnect: 'session' option: sessionStorage not available";}else throw"invalid 'reconnect' option value "+a.reconnect;var t=d(function(a){this.shared&&"slave"==this.shared.role||k.setItem(h,a)},this);this.lastMessageId=k.getItem(h)}else t=function(){};var n=
d(function(){this.running&&this.stop();this.shared&&"master"==this.shared.role&&this.shared.setWithId("status","disconnected")},this);e.addEventListener("beforeunload",n,!1);e.addEventListener("DOMContentLoaded",function(){e.removeEventListener("beforeunload",n,!1);e.addEventListener("unload",n,!1)},!1);var g=this.shared?d(function(a,b){"master"==this.shared.role&&("message"==a?(this.shared.set("msg:id",b[1]&&b[1].id||""),this.shared.set("msg:content-type",b[1]&&b[1]["content-type"]||""),this.shared.set("msg",
b[0])):"error"!=a&&("connecting"==a?this.shared.setWithId("status","connecting"):"connect"==a?this.shared.setWithId("status","connected"):"reconnect"==a?this.shared.setWithId("status","reconnecting"):"disconnect"==a&&this.shared.setWithId("status","disconnected")))},this):function(){};var l,m=d(function(){l||!this.running||!this.reconnect||this.transport.reconnecting||this.transport.doNotReconnect?g("disconnect"):(g("reconnect"),l=e.setTimeout(d(function(){l=null;this.stop();this.start()},this),this.reconnectTimeout))},
this);this.on("message",function a(a,b){(this.lastMessageId=b.id)&&t(b.id);g("message",[a,b])});this.on("error",function(a,b){m(a,b);g("error",[a,b])});this.on("connect",function(){this.connected=!0;g("connect")});this.on("__disconnect",function(a,b){this.connected=!1;this.emit("disconnect",a,b);m(a,b)})}function x(b,a){if(a){var c=b.match(/(\?.*)$/);b+=(c?"&":"?")+"last_event_id="+encodeURIComponent(a)}return b}function w(b){var a=0,c;if(b)for(c in b)b.hasOwnProperty(c)&&a++;return a}var y={};(function(){function b(a,
b,h){a[b]=a[b]||h}var a=["responseType","withCredentials","timeout","onprogress"];y.ajax=function(c,f){function h(a,b){return function(){g||(f(l.status===q?a:l.status,0===l.status?"Error":l.response||l.responseText||b,l),g=!0)}}var k=c.headers||{},d=c.body,n=c.method||(d?"POST":"GET"),g=!1;var l=c.cors&&e.XDomainRequest&&!/MSIE 1/.test(navigator.userAgent)?new XDomainRequest:e.XMLHttpRequest?new XMLHttpRequest:void 0;l.open(n,c.url,!0);var m=l.onload=h(200);l.onreadystatechange=function(){4===l.readyState&&
m()};l.onerror=h(null,"Error");l.ontimeout=h(null,"Timeout");l.onabort=h(null,"Abort");d&&(b(k,"X-Requested-With","XMLHttpRequest"),e.FormData&&d instanceof e.FormData||b(k,"Content-Type","application/x-www-form-urlencoded"));n=0;for(var r=a.length,p;n<r;n++)p=a[n],c[p]!==q&&(l[p]=c[p]);for(p in k)l.setRequestHeader(p,k[p]);l.send(d);return l}})();g.prototype.on=g.prototype.addEventListener=function(b,a){return this._callbacks=this._callbacks||{},(this._callbacks["$"+b]=this._callbacks["$"+b]||[]).push(a),
this};g.prototype.once=function(b,a){function c(){this.off(b,c);a.apply(this,arguments)}return c.fn=a,this.on(b,c),this};g.prototype.off=g.prototype.removeListener=g.prototype.removeAllListeners=g.prototype.removeEventListener=function(b,a){if(this._callbacks=this._callbacks||{},0==arguments.length)return this._callbacks={},this;var c=this._callbacks["$"+b];if(!c)return this;if(1==arguments.length)return delete this._callbacks["$"+b],this;for(var f,h=0;h<c.length;h++)if(f=c[h],f===a||f.fn===a){c.splice(h,
1);break}return this};g.prototype.emit=function(b){this._callbacks=this._callbacks||{};var a=[].slice.call(arguments,1),c=this._callbacks["$"+b];if(c){c=c.slice(0);for(var f=0,h=c.length;h>f;++f)c[f].apply(this,a)}return this};g.prototype.listeners=function(b){return this._callbacks=this._callbacks||{},this._callbacks["$"+b]||[]};g.prototype.hasListeners=function(b){return!!this.listeners(b).length};var d=Function.prototype.bind?function(b,a){return b.bind(a)}:function(b,a){return function(){b.apply(a,
arguments)}},r={};"use strict";g(m.prototype);var u=function(){var b={url:null,msgid:null,headers:{}},a;for(a in m.prototype.SubscriberClass)"__slave"!=a&&(b[a]={});return b};m.prototype.initializeTransport=function(b){b&&(this.desiredTransport=b);if(this.shared&&"slave"==this.shared.role)this.transport=new this.SubscriberClass.__slave(d(this.emit,this));else{b=d(function(a){if(!this.SubscriberClass[a])throw"unknown subscriber type "+a;try{return this.transport=new this.SubscriberClass[a](d(this.emit,
this))}catch(f){}},this);var a;if(this.desiredTransport)for(a=0;a<this.desiredTransport.length&&!b(this.desiredTransport[a]);a++);else for(a in this.SubscriberClass)if(this.SubscriberClass.hasOwnProperty(a)&&"_"!=a[0]&&b(a))break}if(!this.transport)throw"can't use any transport type";};var v;m.prototype.start=function(){if(this.running)throw"Can't start NchanSubscriber, it's already started.";this.starting=!0;if(this.shared){if(r[this.url]&&r[this.url]!=this)throw"Only 1 shared subscriber allowed per url per window/tab.";
r[this.url]=this;if(!this.shared.role){var b=this.shared.getWithId("status");v=d(function(a){this.shared.matchEventKeyWithId(a,"status")?"disconnected"==this.shared.stripIdFromVal(a.newValue)&&"slave"==this.shared.role&&this.shared.maybePromoteToMaster():"master"==this.shared.role&&this.shared.matchEventKeyWithId(a,"master:created")&&a.newValue&&this.shared.demoteToSlave()},this);e.addEventListener("storage",v);"disconnected"==b?this.shared.maybePromoteToMaster():(this.shared.setRole(b?"slave":"master"),
this.initializeTransport())}"master"==this.shared.role?(this.shared.setWithId("status","connecting"),this.transport.listen(this.url,this.lastMessageId),this.running=!0,this.starting=!1,this.shared.masterIntervalCheckID=e.setInterval(d(function(){this.shared.setWithId("master:lastSeen",(new Date).getTime()/1E3)},this),.8*this.shared.masterCheckInterval)):"slave"==this.shared.role&&(this.transport.listen(this.url,this.shared),this.running=!0,this.starting=!1,this.shared.masterIntervalCheckID=e.setInterval(d(function(){var a=
parseFloat(this.shared.getWithId("master:lastSeen"));(!a||a<(new Date).getTime()/1E3-this.shared.masterCheckInterval/1E3)&&this.shared.maybePromoteToMaster()},this),this.shared.masterCheckInterval))}else this.transport||this.initializeTransport(),this.transport.listen(this.url,this.lastMessageId),this.running=!0,this.starting=!1;return this};m.prototype.stop=function(){if(!this.running)throw"Can't stop NchanSubscriber, it's not running.";this.running=!1;v&&e.removeEventListener("storage",v);this.transport.cancel();
this.shared&&(delete r[this.url],this.shared.masterIntervalCheckID&&(clearInterval(this.shared.masterIntervalCheckID),this.shared.masterIntervalCheckID=null));return this};m.prototype.SubscriberClass={websocket:function(){function b(a){WebSocket;this.listener=null;this.emit=a;this.name="websocket";this.opt=u();this.opt.headers["Sec-WebSocket-Protocol"]="ws+meta.nchan"}b.prototype.setup=function(){this.emit("transportSetup",this.opt,this.name);if(1!=w(this.opt.headers)&&"Sec-WebSocket-Protocol"in this.opt.headers)throw"WebSocket only supports one header; Sec-WebSocket-Protocol";
};b.prototype.websocketizeURL=function(a){var b=a.match(/^((\w+:)?\/\/([^/]+))?(\/)?(.*)/);a=b[2];var f=b[3],h=b[4];b=b[5];if("object"==typeof window)var k=window.location;else"object"==typeof document&&(k=document.location);!a&&k&&(a=k.protocol);"https:"==a?a="wss:":"http:"==a?a="ws:":"ws:"!=a&&(a="wss:");!f&&k&&(f=k.host);b=h?"/"+b:k?k.pathname.match(/(.*\/)[^/]*/)[1]+b:"/"+b;return a+"//"+f+b};b.prototype.listen=function(a,b){if(this.listener)throw"websocket already listening";this.opt.url=a;this.opt.msgid=
b;this.setup();a=this.websocketizeURL(this.opt.url);a=x(a,this.opt.msgid);var c=this.listener=new WebSocket(a,this.opt.headers["Sec-WebSocket-Protocol"]);this.emit("transportNativeCreated",c,this.name);c.onmessage=d(function(a){if(a.data instanceof Blob){var b=a.data.slice(0,255),c=new FileReader;c.addEventListener("loadend",d(function(){var b=c.result.match(/^id: (.*)\n(content-type: (.*)\n)?\n/m);this.emit("message",a.data.slice(b[0].length),{id:b[1],"content-type":b[3]})},this));c.readAsText(b)}else b=
a.data.match(/^id: (.*)\n(content-type: (.*)\n)?\n/m),this.emit("message",a.data.substr(b[0].length),{id:b[1],"content-type":b[3]})},this);c.onopen=d(function(a){this.emit("connect",a)},this);c.onerror=d(function(a){this.emit("error",a,c);this.listener=null},this);c.onclose=d(function(a){this.emit("__disconnect",a);this.listener=null},this)};b.prototype.cancel=function(){this.listener&&(this.emit("transportNativeBeforeDestroy",this.listener,this.name),this.listener.close(),this.listener=null)};return b}(),
eventsource:function(){function b(a){EventSource;this.listener=null;this.emit=a;this.name="eventsource";this.opt=u();this.opt.eventsource.withCredentials=!1}b.prototype.setup=function(){this.emit("transportSetup",this.opt,this.name);if(0!=w(this.opt.headers))throw"EventSource does not support headers";};b.prototype.listen=function(a,b){if(this.listener)throw"there's a ES listener running already";this.opt.url=a;this.opt.msgid=b;this.setup();a=x(this.opt.url,this.opt.msgid);a=this.listener=new EventSource(a,
this.opt.eventsource);this.emit("transportNativeCreated",a,this.name);a.onmessage=d(function(a){this.emit("message",a.data,{id:a.lastEventId})},this);a.onopen=d(function(a){this.reconnecting=!1;this.emit("connect",a)},this);a.onerror=d(function(a){this.listener.readyState!=EventSource.CONNECTING||this.reconnecting?this.emit("__disconnect",a):this.reconnecting||(this.reconnecting=!0,this.emit("__disconnect",a))},this)};b.prototype.cancel=function(){this.listener&&(this.emit("transportNativeBeforeDestroy",
this.listener,this.name),this.listener.close(),this.listener=null)};return b}(),longpoll:function(){function b(a){this.longPollStartTime=this.nextRequestTimer=this.pollingRequest=this.reqStartTime=this.req=null;this.maxLongPollTime=3E5;this.emit=a;this.name="longpoll";this.opt=u();this.opt.longpoll.pollDelay=0;this.opt.longpoll.method="GET"}b.prototype.setup=function(){this.emit("transportSetup",this.opt,this.name)};b.prototype.listen=function(a,b){if(this.req)throw"already listening";this.opt.url=
a;(this.opt.msgid=b)&&(this.opt.headers.Etag=b);this.setup();var c=d(function(a,b){a&&(this.opt.headers[b]=a)},this);this.pollingRequest=d(function(){this.req&&this.emit("transportNativeBeforeDestroy",this.req,this.name);this.nextRequestTimer=null;this.reqStartTime=(new Date).getTime();this.req=y.ajax({url:this.opt.url,method:this.opt.longpoll.method,headers:this.opt.headers},h);this.emit("transportNativeCreated",this.req,this.name)},this);var h=d(function(a,b,d){c(d.getResponseHeader("Last-Modified"),
"If-Modified-Since");c(d.getResponseHeader("Etag"),"If-None-Match");200<=a&&210>=a?(a=d.getResponseHeader("Content-Type"),this.parseMultipartMixedMessage(a,b,d)||this.emit("message",b||"",{"content-type":a,id:this.msgIdFromResponseHeaders(d)}),this.req&&(0==this.opt.longpoll.pollDelay?this.pollingRequest():this.nextRequestTimer=e.setTimeout(this.pollingRequest,this.opt.longpoll.pollDelay))):0==a&&"Error"==b&&4==d.readyState||null===a&&"Abort"!=b?(this.emit("__disconnect",a||0,b),this.cancel()):null!==
a?(this.emit("error",a,b),this.cancel()):(this.cancel(),this.emit("__disconnect"))},this);this.pollingRequest();this.emit("connect");return this};b.prototype.parseMultipartMixedMessage=function(a,b,d){a=a&&a.match(/^multipart\/mixed;\s+boundary=(.*)$/);if(!a)return!1;b=b.split("--"+a[1]);if(""!=b[0]||!b[b.length-1].match(/--\r?\n/))throw"weird multipart/mixed split";b=b.slice(1,-1);for(var c in b){a=b[c].match(/^(.*)\r?\n\r?\n([\s\S]*)\r?\n$/m);var f=a[1].split("\n"),e={},g;for(g in f){var m=f[g].match(/^([^:]+):\s+(.*)/);
m&&"Content-Type"==m[1]&&(e["content-type"]=m[2])}c==b.length-1&&(e.id=this.msgIdFromResponseHeaders(d));this.emit("message",a[2],e)}return!0};b.prototype.msgIdFromResponseHeaders=function(a){var b=a.getResponseHeader("Last-Modified");a=a.getResponseHeader("Etag");return b?""+Date.parse(b)/1E3+":"+(a||"0"):a?a:null};b.prototype.cancel=function(){this.req&&(this.emit("transportNativeBeforeDestroy",this.req,this.name),this.req.abort(),this.req=null);this.cancelPendingPollRequest();return this};b.prototype.cancelPendingPollRequest=
function(){this.nextRequestTimer&&(e.clearTimeout(this.nextRequestTimer),this.nextRequestTimer=null)};b.prototype.reschedulePendingPollRequest=function(a){this.opt.longpoll.pollDelay=a;this.cancel();0===this.opt.longpoll.pollDelay?this.pollingRequest():this.nextRequestTimer=e.setTimeout(this.pollingRequest,this.opt.longpoll.pollDelay)};return b}(),__slave:function(){function b(a){this.emit=a;this.doNotReconnect=!0;this.shared=null;this.name="__slave";this.opt=u()}b.prototype.setup=function(){this.emit("transportSetup",
this.opt,this.name);if(0!=w(this.opt.headers))throw"__slave does not support headers";};b.prototype.listen=function(a,b){this.shared=b;this.opt.url=a;this.setup();this.statusChangeChecker=d(function(a){if(this.shared.matchEventKey(a,"msg")){a=this.shared.get("msg:id");var b=this.shared.get("msg:content-type"),c=this.shared.get("msg");this.emit("message",c,{id:""==a?q:a,"content-type":""==b?q:b})}},this);e.addEventListener("storage",this.statusChangeChecker)};b.prototype.cancel=function(){e.removeEventListener("storage",
this.statusChangeChecker)};return b}()};return m});
